# Figure 3: Tradeoff axes defined by PLS regression coefficients

In [1]:
import numpy as np
import pandas as pd

import bokeh.io
import bokeh.plotting
from bokeh.models import ColumnDataSource
bokeh.io.output_notebook()

import iqplot

import sys
sys.path.insert(0, '../analysis')
from pls_tradeoff import run_pls
from plot_gsea import plot_gsea

from sklearn.preprocessing import StandardScaler
from sklearn.cross_decomposition import PLSRegression

from tqdm import tqdm

## Figure 3A: ribosomal vs metabolic proteome fraction (Belliveau et al., 2021)

Adapted from Github available from Belliveau et al. No extra processing steps were done.

## Figure 3B: PLS-derived tradeoff axes for E. coli mRNA data

### Plot tradeoff axes

**Load growth data**

In [2]:
df_hwa_gr = pd.read_excel('../data/e.coli/science.abk2066_table_s3.xlsx', sheet_name = 0)
growth_map = df_hwa_gr.set_index("Sample ID")["Growth rate (1/h)"]

**Load mRNA data**

In [3]:
df_hwa_mrna = pd.read_excel("../data/e.coli/science.abk2066_table_s3.xlsx", sheet_name = 1)
df_hwa_mrna.head(2)

,gene,locus,gene length (nt),c4,c4_1,c3_1,c3,c2,c2_1,c1,...,r3_1,r5,r4,r2_1,r3,r2,r1_1,r1,r0,r0_1
0,aaeA,b3241,933,0.000003,0.000002,0.000002,0.000003,0.000003,0.000003,0.000003,...,0.000005,0.000005,0.000005,0.000005,0.000004,0.000005,0.000003,0.000004,0.000003,0.000003
1,aaeB,b3240,1968,0.000003,0.000002,0.000003,0.000002,0.000002,0.000002,0.000002,...,0.000006,0.000005,0.000005,0.000005,0.000005,0.000004,0.000004,0.000004,0.000003,0.000003

**Process mRNA df and add growth values**

In [4]:
df_hwa_mrna = df_hwa_mrna.drop(['locus', 'gene length (nt)'], axis = 1)
df_hwa_mrna_T = df_hwa_mrna.T
df_hwa_mrna_T.columns = df_hwa_mrna_T.iloc[0].values

# drop sample with no growth rate
df_hwa_mrna_T = df_hwa_mrna_T.drop(['gene', 'a4_1.1']) 

# add growth rate values
df_hwa_mrna_T['growth_rate'] = df_hwa_mrna_T.index.map(growth_map)

df_hwa_mrna_T.head(2)

,aaeA,aaeB,aaeR,aaeX,aas,aat,abgA,abgB,abgR,abgT,...,znuA,znuB,znuC,zraP,zraR,zraS,zupT,zur,zwf,growth_rate
c4,0.000003,0.000003,0.000021,0.000016,0.000029,0.000049,0.000002,0.000005,0.00005,0.000004,...,0.000084,0.000026,0.000042,0.000027,0.000007,0.00001,0.00008,0.000039,0.000166,0.30
c4_1,0.000002,0.000002,0.000017,0.000008,0.000032,0.000047,0.000003,0.000004,0.000043,0.000005,...,0.000085,0.00003,0.000038,0.000005,0.000007,0.000008,0.000092,0.00004,0.000182,0.39

**Define separate dfs for each condition**

In [5]:
# carbon
df_c = df_hwa_mrna_T[df_hwa_mrna_T.index.str.startswith('c')]
# ammonia
df_a = df_hwa_mrna_T[df_hwa_mrna_T.index.str.startswith('a')]
# chloramphenicol
df_r = df_hwa_mrna_T[df_hwa_mrna_T.index.str.startswith('r')]

**Plot**

In [6]:
beta_df, p_scatter, p_hist = run_pls(df_c, t=0, condition = 'Carbon')

G+/G- correlation: -0.7779168269790089 | G+ genes: 1720 | G- genes: 2543

In [7]:
beta_df, p_scatter, p_hist = run_pls(df_a, t=0, condition = 'Nitrogen')

G+/G- correlation: -0.6066780034659189 | G+ genes: 1208 | G- genes: 3053

In [8]:
beta_df, p_scatter, p_hist = run_pls(df_r, t=0, condition = 'Chloramphenicol')

G+/G- correlation: -0.9012271676081604 | G+ genes: 2268 | G- genes: 1997

### Plot GSEA results

We used the Broad GSEA tool to get GSEA reports.

* The GMT file used can be found: https://github.com/ELTEbioinformatics/GMT_files_for_mulea/blob/main/GMT_files/Escherichia_coli_83333/GO_BP_Escherichia_coli_GeneSymbol.gmt

* Used 5000 permutations


Results stored in analysis/ folder

In [9]:
pos_df_c = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_pos_carbon.tsv", sep="\t")
neg_df_c = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_neg_carbon.tsv", sep="\t")
p, size_legend = plot_gsea(pos_df_c, neg_df_c, obo_file='../analysis/GSEA_outputs/go-basic.obo')

In [10]:
pos_df_a = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_pos_ammonia.tsv", sep="\t")
neg_df_a = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_neg_ammonia.tsv", sep="\t")
p, size_legend = plot_gsea(pos_df_a, neg_df_a, obo_file='../analysis/GSEA_outputs/go-basic.obo')

In [11]:
pos_df_r = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_pos_chloramphenicol.tsv", sep="\t")
neg_df_r = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_neg_chloramphenicol.tsv", sep="\t")
p, size_legend = plot_gsea(pos_df_r, neg_df_r, obo_file='../analysis/GSEA_outputs/go-basic.obo')

## Figure 3C: PLS-derived tradeoff axes for S. pombe mRNA data

### Plot tradeoff axes

**Load mRNA and growth data**

In [12]:
df_kleijn_mrna = pd.read_excel('../data/s.pombe/normalized_mRNA_counts.xlsx')
df_kleijn_gr = pd.read_excel('../data/s.pombe/growth_info.xlsx')

**Process dfs**

In [13]:
df_kleijn_mrna['sample rep'] = df_kleijn_mrna['medium'] + df_kleijn_mrna['replicate'].fillna(0).astype(int).astype(str)
df_kleijn_mrna = df_kleijn_mrna[['PomBaseID', 'sample rep', 'raw_counts']]

# remove last row, extraneous
df_kleijn_mrna = df_kleijn_mrna.iloc[:-1]

df_kleijn_gr['sample rep'] = df_kleijn_gr['medium'] + df_kleijn_gr['replicate'].astype(str)

**Merge dfs**

In [14]:
df_kleijn_merge = df_kleijn_mrna.merge(df_kleijn_gr[['sample rep', 'growth_rate']], on='sample rep', how='left')
df_kleijn_merge = df_kleijn_merge.iloc[:-1]

# Pivot to wide format: rows = sample rep, columns = PomBaseID, values = raw_counts
df_wide = df_kleijn_merge.pivot_table(
    index='sample rep',
    columns='PomBaseID',
    values='raw_counts'
).reset_index()

# Get unique growth rate per sample rep
growth = df_kleijn_gr[['sample rep', 'growth_rate']].drop_duplicates()

# Merge growth_rate back into the wide-format DataFrame
df_wide = df_wide.merge(growth, on='sample rep', how='left')
df_wide.head(2)

,sample rep,SPAC1002.01,SPAC1002.02,SPAC1002.03c,SPAC1002.04c,SPAC1002.05c,SPAC1002.06c,SPAC1002.07c,SPAC1002.08c,SPAC1002.09c,...,SPSNORNA.54,SPSNRNA.01,SPSNRNA.02,SPSNRNA.03,SPSNRNA.04,SPSNRNA.05,SPSNRNA.06,SPSNRNA.07,spncrna.9001,growth_rate
0,Amm1,184.0,1017.0,6122.0,717.0,478.0,7.0,2496.0,727.0,21305.0,...,206.0,11.0,15.0,26.0,8.0,1.0,9.0,57.0,1737.0,0.232753
1,Amm2,124.0,900.0,4969.0,700.0,468.0,6.0,2138.0,615.0,17663.0,...,219.0,3.0,12.0,35.0,4.0,4.0,10.0,64.0,929.0,0.284854

**Plot PLS with no thresholding**

In [15]:
df_input = df_wide.set_index('sample rep')
beta_df, p_scatter, p_hist = run_pls(df_input, t=0, condition='s.pombe')

G+/G- correlation: 0.06965644083238576 | G+ genes: 3266 | G- genes: 3493

**Run permutation test to identify threshold**

In [16]:
# define data
y = df_input['growth_rate'].values
X = df_input.drop(columns=['growth_rate']).values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# run permutation test
n_perms = 1000
null_betas = []

for _ in tqdm(range(n_perms)):
    y_perm = np.random.permutation(y)
    pls_perm = PLSRegression(n_components=2)
    pls_perm.fit(X_scaled, y_perm)
    null_betas.append(pls_perm.coef_.flatten())

null_betas = np.array(null_betas)  # shape (n_perms, p)

# threshold = 95th percentile of null |beta| distribution
tau = np.percentile(np.abs(null_betas), 95)
tau

100%|██████████████████████████████████████| 1000/1000 [00:03<00:00, 301.07it/s]

6.012866821449416e-05

**Plot PLS with thresholding**

In [17]:
# use this threshold for consistency
# every permutation run gives a slightly different value

tau = 6.010127746160799e-05

In [18]:
beta_df, p_scatter, p_hist = run_pls(df_input, t=6.010127746160799e-05, condition='S.pombe')

G+/G- correlation: -0.6916874002838713 | G+ genes: 22 | G- genes: 4

### Plot GSEA results

We used the Broad GSEA tool to get GSEA reports.

* The GMT file used can be found: https://github.com/ELTEbioinformatics/GMT_files_for_mulea/blob/main/GMT_files/

* Used 5000 permutations


Results stored in analysis/ folder

In [19]:
pos = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_pos_spombe.tsv", sep="\t")
neg = pd.read_csv("../analysis/GSEA_outputs/gsea_report_for_na_neg_spombe.tsv", sep="\t")

In [20]:
p, size_legend = plot_gsea(pos, neg, obo_file='../analysis/GSEA_outputs/go-basic.obo', plot_width = 1400 )

In [21]:
%load_ext watermark
%watermark -v -p numpy,pandas,bokeh,iqplot,sys,sklearn,tqdm

Python implementation: CPython
Python version       : 3.12.2
IPython version      : 8.27.0

numpy  : 1.26.4
pandas : 2.2.2
bokeh  : 3.9.1
iqplot : 0.3.7
sys    : 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
sklearn: 1.5.1
tqdm   : 4.66.5